name: Package Extension

on:
  push:
    branches:
      - firefox

jobs:
  package-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package extension
        run: |
          mkdir -p build/firefox
          cp -r manifest.json *html *js icons/ icon.svg build/firefox/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaultPass_firefox
          path: build/firefox/

